"""empty message

Revision ID: 69aca8173f68
Revises: 
Create Date: 2025-02-24 00:04:03.197666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69aca8173f68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Category_category_name'), 'Category', ['category_name'], unique=True)
    op.create_index(op.f('ix_Category_id'), 'Category', ['id'], unique=False)
    op.create_table('UserProfile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('courier', 'client', 'owner', name='userrole'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('CourierReview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Enum('review1', 'review2', 'review3', 'review4', 'review5', name='reviewchoices'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['UserProfile.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['UserProfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('role', sa.Enum('type1', 'type2', 'type3', 'type4', name='orderrole'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['UserProfile.id'], ),
    sa.ForeignKeyConstraint(['courier_id'], ['UserProfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=40), nullable=False),
    sa.Column('store_description', sa.Text(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('store_image', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['UserProfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['Store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Courier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('courier1', 'courier2', name='courierrole'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['Order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['UserProfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=40), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('product_image', sa.String(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['Store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProductCombo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['Store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('StoreReview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('rating', sa.Enum('review1', 'review2', 'review3', 'review4', 'review5', name='reviewchoices'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['UserProfile.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['Store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StoreReview')
    op.drop_table('ProductCombo')
    op.drop_table('Product')
    op.drop_table('Courier')
    op.drop_table('Contact')
    op.drop_table('Store')
    op.drop_table('Order')
    op.drop_table('CourierReview')
    op.drop_table('UserProfile')
    op.drop_index(op.f('ix_Category_id'), table_name='Category')
    op.drop_index(op.f('ix_Category_category_name'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
